# Site settings
title: 개발자를 꿈꾸는 임택균의 포트폴리오
email: xorrbs100@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xorrbs100.githob.io/portfolio/tg" # the base hostname & protocol for your site

# User setting
owner:  ImTaekGyoon
email:  xorrbs100@naver.com
github_username: xorrbs100

  # Feel free to add more lines here 
telephone: 010-6680-0918
copyright:

# Build settings
markdown: kramdown